#!/bin/bash

set -e
set -o pipefail

# --- Parse flags ---
USE_GITLAB=false
for arg in "$@"; do
  case "$arg" in
    --gitlab)
      USE_GITLAB=true
      shift
      ;;
  esac
done

if $USE_GITLAB
then
    glab mr list | grep -v 'No open merge' | grep . || true > /tmp/prlist
else
    gh pr list > /tmp/prlist
    baseurl=$(git remote get-url origin | sed 's/\.git//g')
    cat /tmp/prlist | awk '{print $1}' | sed "s|^|$baseurl/pull/|g" | sponge -a /tmp/prlist
fi

if [[ -s /tmp/prlist ]]
then
    echo "Found open PRs"
    cat /tmp/prlist
    read -p "Continue" res
fi

if $USE_GITLAB
then
    file=project1/gitlab.tf
else
    file=project1/main.tf
fi

git checkout main
git pull --ff-only

curnum=$(cat $file | grep my-resource -A1 | grep input | cut -f 2 -d '"')

newnum=$(( $curnum + 1))

sed -i '' "s/input = \"$curnum\"/input = \"$newnum\"/g" $file

branch="bump_input_${newnum}_$(date +%s)"
if $USE_GITLAB
then
    remote="gitlab"
else
    remote="origin"
fi

git add $file
git checkout -b $branch
git commit -m "Bump input $newnum"
git push $remote $branch

if $USE_GITLAB
then
    glab mr create --fill
else
    gh pr create --title "Bump input $newnum" --body "Bump"
fi
